### ISSUE TITLE
After deleting item: c.reset is not a function (in finishDelete)

### ISSUE THREAD

**Issue by ErikvdBurgwal** [tabalinas/jsgrid#867]
Hi,
I try to delete a row from the grid (from a Control field with delete button created with this._createDeleteButton(item) ). The ajax-call is executed as expected (using the typical REST controller from the documentation). However, after the POST has completed, I get the following error;

```
jquery-3.1.1.js:3846 jQuery.Deferred exception: grid.reset is not a function TypeError: grid.reset is not a function
    at DirectLoadingStrategy.finishDelete (http://localhost:38662/Scripts/jsgrid/jsgrid.js:1616:18)
    at Grid.<anonymous> (http://localhost:38662/Scripts/jsgrid/jsgrid.js:1382:36)
    at proxy (http://localhost:38662/Scripts/jquery-3.1.1.js:502:14)
    at fire (http://localhost:38662/Scripts/jquery-3.1.1.js:3305:31)
    at Object.fireWith [as resolveWith] (http://localhost:38662/Scripts/jquery-3.1.1.js:3435:7)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:38662/Scripts/jquery-3.1.1.js:3765:36)
    at Object.<anonymous> (http://localhost:38662/Scripts/jsgrid/jsgrid.js:40:27)
    at mightThrow (http://localhost:38662/Scripts/jquery-3.1.1.js:3570:29)
    at process (http://localhost:38662/Scripts/jquery-3.1.1.js:3638:12) undefined
```
Additionally, the grid is not refreshed and the loading-window not removed.

I have no clue where to start looking into cause/solution for this issue, could you please help me towards finding the cause of this problem?

Thanks,
Erik

**Comment by tabalinas** [comment]
Could it be that you redefined `reset` method on the grid. Are you sure there is no `reset` config parameter in the grid config?

Anyway, it's hard to help w/o the jsgrid config. Providing a jsfiddle reproducing the issue would be even more helpful.

**Comment by ErikvdBurgwal** [comment]
Thanks for your response. I have created a jsfiddle to reproduce the issue. It seems to be related to setting the locale, although I do not yet understand why/how.

https://jsfiddle.net/erikvdb/px6rme07/20/

When you try to delete a record, you'll get the error as described before. When you comment the last line in the fiddle (    jsGrid.locale('nl');   ), the error does not occur.

Hopefully you can help me find the problem? Thanks!

**Comment by ErikvdBurgwal** [comment]
Ok, the answer was already in front of my face. 

The  'additional' translation texts where redefining the reset-method on the grid as you suggested. 
Thanks for helping me out!
